### PR TITLE
Create prime_check

### PR DESCRIPTION
**Pull request by ghost**
To solve issue: Create a program to let us to know if a number is prime or not.

Features:

The program will be written in Python language.
The program input should be a number written by the user.
The program output should be "YES" if the number is prime, or "NO" if it isn't.

### CODE REVIEW

**Comment by HarryJamesRobson** [comment]
Solve issue: Create a program to let us to know if a number is prime or not.

Features:

The program will be written in Python language.
The program input should be a number written by the user.
The program output should be "YES" if the number is prime, or "NO" if it isn't.

**Comment by ghost** [comment]
@jneirar

**Comment by jneirar** [comment]
Thanks sir, but sorry. This is a homework from my university.

**Comment by ghost** [comment]
Ah right, well there's your answer.

**Pull request closed without merging**
